### PR TITLE
fix bug with unexpected indentation in peerreview mode

### PR DESCRIPTION
**Pull request by loganwhite**
The Chinese keyword label experiencing an unexpected indentation in the peerreview mode. For more information see #81.

### CODE REVIEW

**Comment by NigelBoxing** [comment]
> The Chinese keyword label experiencing an unexpected indentation in the peerreview mode. For more information see #81.

install下的buptgraduatethesis.dtx 也需要修改的

**Comment by loganwhite** [comment]
@NigelBoxing Thanks for reminding me, since my project structure has been changed significantly. It seems that I didn't use `buptgraduatethesis.dtx `. Please feel free to make modifications, thanks. I'm done with it.

**Comment by qin-nz** [comment]
We only accept modification to source code, not the release zip file.

**Comment by loganwhite** [comment]
Thanks for providing the "time-saving auto" installation process for the project. But if I were a contributor, I would prefer not to use it 'cause it seems a bit redundant.

Again, I would like to thank all contributors for their wonderful works and volunteered times spend on this project. And I do appreciate all the great help received from this community.

**Pull request closed without merging**
